### ISSUE TITLE
Utilitzar el bloc IdOtro per a NIFs no censats a l'AEAT

### ISSUE THREAD

**Issue by gdalmau** [gisce/sii#43]
Pàgina 13
http://www.agenciatributaria.es/static_files/AEAT/Contenidos_Comunes/La_Agencia_Tributaria/Modelos_y_formularios/Suministro_inmediato_informacion/FicherosSuministros/V_07/PP_F_PRUEBAS_200417_Modo_compatibilidad.pdf

> - Se incorpora la posibilidad de incluir NIF cuya identificación figura incompleta para las facturas emitidas.
> 
> Para los casos en que se haya rechazado una factura emitida en un segundo reintento, porque la información de identificación del destinatario (NIF y nombre) no figure censada en la AEAT, la forma de proceder para enviar dicha factura se Departamento de Gestión Tributaria 13 no figure censada en la AEAT, la forma de proceder para enviar dicha factura se realizará a través del bloque IdOtro con los siguientes contenidos:
> 
> Código país: ES
> Clave ID: 07. No censado
> Número Id: NIF no censado del receptor de la factura
> Apellidos y nombre: Nombre del no censado receptor de la factura.
> 
> Siempre que se utilice esta clave de identificación 07 el registro quedará aceptado con errores.

**Comment by gdalmau** [comment]
@mroig @MiquelIR Per tal d'utilitzar el bloc IDOtro es necessita saber a l'hora de serialitzar l'objecte. Afegim un paràmetre a l'hora d'enviar la factura?

```python
from sii.server import SiiService

SiiService.send(invoice, nif_not_validated=True)
```

**Comment by MiquelIR** [comment]
@gdalmau Sí que serà necessari fer-ho. Amb un parámetre nou, em sembla una bona manera.

**Comment by mroig** [comment]
Jo ho guardaria en un camp de res_partner que es diria `registered_aeat`.
