### ISSUE TITLE
Posició Fiscal no determina tipus d'operació

### ISSUE THREAD

**Issue by totaler** [gisce/sii#51]
La posició fiscal no pot determinar el tipus d'operació RE. Aquest valor és únic per client, però li podem fer diferents tipus de factures que corresponguin a diferents claus. Per exemple li fem la factura elèctrica i una factura d'un lloguer de local. Son dos claus diferents per SII però seria la mateixa posició fiscal.

**Comment by totaler** [comment]
De totes formes en paral·lel tinc la consulta oberta amb administració, per que em confirmin aquest cas.

**Comment by totaler** [comment]
Confirmat. Al mateix client li fem factures de tipus General i/o De lloguer amb retenció o sense retenció depenent de si és persona física o jurídica. Tenim dels dos casos.

Us proposo un sistema de dues passes. Determinar la clau de l'operació per diari i si existeix una posició fiscal associada i té un valor de clau informat i diferent, fer servir aquest mateix. D'aquesta forma crec que cobrim tots els casos (lloguers o canàries, per exemple). Recordeu que la posició fiscal no és un camp obligatori a les factures i que pot no estar informat.

**Comment by totaler** [comment]
@gdalmau @ecarreras  he vist que heu fet una sèrie de canvis sobre la clau de règim especial, però encara no hi ha resolt el tema que us comentava ja que ara es mira la posició fiscal del partner de la factura abans de la del diari. Segons he vist:

1. Posició fiscal de la factura
2. Posició fiscal del partner de la factura
3- Clau associada al diari

Tots els partners tenen posició fiscal (camp property), per tant mai mirarà la del diari. Estem igual que al principi. Per altra banda el control es fa diferent a les factures rebudes on no es controla que no pugui haver la clau configurada, com si es fa a les emeses. Ara mateix estic fent feina amb master, per si no miro el codi correcte.

**Comment by gdalmau** [comment]
@totaler El que hem decidit és afegir el camp `sii_out_clave_regimen_especial` i `sii_in_clave_regimen_especial` a una `account.invoice` que serà la que anirà a buscar la llibreria del SII. Aquest camp s'emplenarà quan es creï la factura amb el valor de la posició fiscal o amb un valor per defecte ('01 Operación de régimen general')

Ho estem desenvolupant aquí https://github.com/gisce/erp/issues/4722

**Comment by gdalmau** [comment]
@totaler Tanco perquè ja s'ha fet un merge al mòdul
