### ISSUE TITLE
Tractament IESE

### ISSUE THREAD

**Issue by totaler** [gisce/sii#52]
No tinc clar el tractament de l'IESE. A l'enviament d'una factura elèctrica calcula aquest diccionari d'impostos
```
{'iva_exento': False, 'iva_no_exento': True, 'no_sujeta_a_iva': True, 'detalle_iva': [{'BaseImponible': 
 70.72, 'CuotaRepercutida': 14.85, 'TipoImpositivo': 0}], 'detalle_iva_exento': {'BaseImponible': 0}, 
 'sujeta_a_iva': True}
```

I l'enviament surt "Aceptado con errores" amb:

[2012] El campo CuotaRepercutida tiene un valor incorrecto para los campos TipoImpositivo y BaseImponible suministrados

**Comment by totaler** [comment]
Fent més proves ho he aclarit. Quan el mòdul account_tax_factor estava actiu no guardava el tax_id a les línies d'impostos. Ja he fet la PR https://github.com/gisce/erp/pull/4685 per arreglar-ho. He pogut pujar factures de diferents tipus correctament. :+1: 

Una qüestió sobre aquest tema. Les factures del primer semestre de 2017, que s'han d'informar durant el segon semestre de 2017 i que no tenen aquest tax_id, heu pensat qualcuna cosa per fer-ho?

**Comment by mroig** [comment]
Exactament, el problema que et donava abans era degut a que el `tax_id` no estava assignat i en aquest cas posava que el tipus impositiu és 0.

Per tant, en una de les seves comprovacions miraven que BaseImponible * TipoImpositivo fos igual a CuotaRepercutida. Com que el TipoImpositivo era 0 el resultat no era correcte.

Per les factures del primer semestre del 2017 el hem fet ha estat executar una comanda sql que posa el `tax_id` segons el nom de l'impost. Ja l'hem passat al vostre servidor de pre i queden 22 línies que no tenen cap `account_tax` amb el mateix nom.

S'haurien de revisar quin id s'ha de posar en aquestes però per la resta ja no hauria d'haver-hi més problemes.
