### ISSUE TITLE
Afegir el camp 'FechaRegContable'

### ISSUE THREAD

**Issue by gdalmau** [gisce/sii#53]
El camp [`FechaRegContable`](https://github.com/gisce/sii/blob/master/sii/resource.py#L153) d'una **_Factura Recibida_** no l'obtenim de la factura, s'ha de definir quin camp és.

**Comment by gdalmau** [comment]
@ecarreras @tinogis @guilleJB @mroig Com obtenim aquest camp en l'ERP?

**Comment by totaler** [comment]
A l'erp la data de registre comptable és el camp "date_invoice". El que necessitem és un camp on guardar la data original de la factura rebuda que no serà "date_invoice" i ara mateix no es pot guardar enlloc.

**Comment by totaler** [comment]
@ecarreras @tinogis @guilleJB @gdalmau aquest tema com ha quedat? Sense aquest camp per guardar la data original de la factura no es poden fer les proves completes.

**Comment by gdalmau** [comment]
@totaler Amb quina data comptabilitzeu les factures de peatges? Amb la data original de la factura o la data d'entrada al sistema (en cas de l'ERP és quan la factura passa de borrador a oberta que crea els assentaments comptables)

**Comment by totaler** [comment]
@gdalmau com totes les factures rebudes, quan es comptabilitza per part del departament d'administració. En el cas de l'erp quan la validem a l'erp i crea l'assentament. A més a més, amb el SII aprofitarem per passar totes les factures rebudes per l'erp, amb el mateix sistema i exportarem al programa comptable.

**Comment by gdalmau** [comment]
@totaler El que farem doncs és afegir un camp addicional a la `account.invoice` (per exemple, `original_date_invoice`) que representi la data de la factura de referència. Així la llibreria del SII agafarà la 'date_invoice' que serà la que s'enviï com a data de registre comptable ([`FechaRegContable`](https://github.com/gisce/sii/blob/master/sii/resource.py#L171)) i la `original_date_invoice` que serà la data en què es va emetre la factura ([`FechaExpedicionFacturaEmisor`](https://github.com/gisce/sii/blob/master/sii/resource.py#L248))

**Comment by totaler** [comment]
@gdalmau Em pareix molt bé.

**Comment by gdalmau** [comment]
Tanco resolt https://github.com/gisce/erp/commit/5f2b86a2a0a0a9117e3e1e011fb0ee5a02b0174d
